[project]
name = "okenaba"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-analytics-data>=0.20.0",
    "pandas>=3.0.0",
]
